export const defaultTheme = {
  blacktColor: "#414141",
  orangeColor: "#FF6633",
  decorGreenColor: "#70C05B",
  decorGreyColor: "#F3F2F1",
  backgroundColor: "#FBF8EC",
  backgroundOfferOrangeColor: "#FCD5BA",
  backgroundOfferGreenColor: "#E5FFDE",
  indent: "40px",
  fornFamily: '"Rubik", "Arial", sans-serif',
  fontSizeDefault: "12px",
  fontWeightDefault: "400",
  pageWidth: "1208px",
  footerHeight: "126px",
}